language: clojure
sudo: false
script:
  - lein test
  - lein with-profile +1.8 test
  - lein with-profile +1.9 test
jdk:
  - openjdk8
  - openjdk11
matrix:
  include:
    - script: lein coverage
      jdk:    openjdk8
    - script: lein eastwood
      jdk:    openjdk8
